FROM denoland/deno:2.5.3

# Playwrightのインストール
RUN deno run --allow-all npm:playwright install chromium

# Claude Codeをdevcontainerで使うための設定
ARG USERNAME=deno

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
  && mkdir /commandhistory \
  && touch /commandhistory/.bash_history \
  && chown -R $USERNAME /commandhistory

# # Set `DEVCONTAINER` environment variable to help with orientation
# ENV DEVCONTAINER=true

# Create workspace and config directories and set permissions
RUN mkdir -p /home/deno/.claude && \
  chown -R deno:deno /home/deno/.claude

# # Install Claude
# RUN npm install -g @anthropic-ai/claude-code