version: '3.8'

services:
  app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      - ..:/workspaces/sbi-portfolio-tracker:cached
      - claude-code-bashhistory:/commandhistory
      - claude-code-config:/home/vscode/.claude
    env_file:
      - ../.env
      - .env
    environment:
      CLAUDE_CONFIG_DIR: /home/vscode/.claude
    user: vscode
    command: sleep infinity

volumes:
  claude-code-bashhistory:
  claude-code-config:
