name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    # CIではenvを指定せずコマンド内で.env.testを上書き

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            node_modules
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.json', 'deno.lock') }}

      - name: Setup and test
        run: |
          deno install
          deno task db:generate
          deno task db:test:setup
          deno task test:unit
          deno task test:integration
          deno task test:coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          fail_ci_if_error: false