name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: denoland/deno:ubuntu

    services:
      postgres-test:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # CIではenvを指定せずコマンド内で.env.testを上書き

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/deno
            node_modules
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.json', 'deno.lock') }}

      - name: Run tests
        run: |
          deno task test

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          fail_ci_if_error: false
